version: "3"

services:
  image: registry.cn-hangzhou.aliyuncs.com/szss/elastic-job-lite-console:2.1.5
    restart: always
    container_name: elasticjob
    hostname: elasticjob
    environment:
      - 'ROOT_USERNAME=root'
      - 'ROOT_PASSWORD=root123'
      - 'GUEST_USERNAME=guest'
      - 'GUEST_PASSWORD=guest123'
    ports:
      - "8899:8899"