server.port: 8081

spring:
  cache:
    redis:
      time-to-live: 100s
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 2s   #操作超时的情况，默认60s
#    cluster.nodes:
#      - 10.10.3.51:2001
#      - 10.10.3.51:2002
#      - 10.10.3.51:2003
#    lettuce.pool:
#      max-active: 10
#      max-idle: 10



