server:
  port: 8081

logging:
  file: ./logs/loc.log

loc.web.springmvc.swagger2:
  restapi:
    base-package: com.loc.framework.springmvc.sample
#  enabled: false

loc.tomcat.shutdown.wait-time: 20

#sentry:
#  dsn: https://public:private@host:port/1

